# Title of your website
title: "Fauz Mechanics"

# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'https://stuffbits-fauzmechanics.github.io/Website_FauzMechanics'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://stuffbits-fauzmechanics.github.io/Website_FauzMechanics/assets/img/'

collections:
  products:
    output: true

  products_catalog:
    output: true

